### ISSUE TITLE
Humanoid floating pelvis in Unity

### ISSUE THREAD

**Issue by sd1026** [MeleeCampz/IMU-Based-Motion-Capturing#3]
Can you please tell me on how can I make the humanoid avatar pelvis to move as player walks. Pelvis stays in air where it is, and the legs move upwards while crouching, squating. I don't want this scenario.

Currently, I am using Unity Engine, which starts to transform the positions of lower limbs from the pelvis position. So, I want to get exactly the same solution you made, but for Unity engine.

I am giving quaternions as rotations to the thighs, shins, and I don't have sensors on feet of the player. I saw in your thesis, that you use PlaceFeetOnGround offset, but Unity engine doesn't have such thing. Could you please tell me the solution.

**Comment by MeleeCampz** [comment]
Hello sd1026,

On the character blueprint there should be an boolean option called "PlaceFootOnGround", which basically lowers the character, so that the lower of the two feet is touching the ground. I don't have the project on my PC right now, but that is also mentioned in my thesis on page 41.

As for unity implementation. The logic is not very complicated. You will have to write a custom MonoBehaviour that compares the y-Position of the right and left foot bone. Take the y-Position that is smaller and move the character by this much in the opposite direction along the y-Axis. So if one foot would be  0.4  and the other would be 0.6 -> move the character by -0.4 along the y-Axis. I would suggest to put this into the Update() method so it get executed every frame.

**Comment by sd1026** [comment]
ThankYou sir, I really appreciate that solution. I will try this now, and tell if that works.

**Comment by sd1026** [comment]
Does this concept goes for walking as for sideways walking and moving the pelvis left or right and forward and backward.

**Comment by MeleeCampz** [comment]
Unfortunately this will not work. There is no positional tracking at all in my setup. 
If you need positional tracking you will have to implemented this on your own.

I would suggest adding an extra sensor like a vive tracker to get an absolute reference position.
Alternatively you could use an algorithm like step detection/estimation to guess where the user moved to (https://elib.dlr.de/91625/1/IPIN_Munoz.pdf)
But yeah, I am sorry to tell you that you will have to come up with a solution on your own for that.

**Comment by sd1026** [comment]
Thanks sir!
